# This is a Render Blueprint that defines the services for the inventory application.
# Render will automatically create and deploy these services when you connect your GitHub repo.

# Databases are defined in their own top-level block
databases:
  - name: inventory-db
    plan: free # Render's free tier is sufficient for this project
    databaseName: inventory_db # Explicitly name the database
    user: inventory_user       # Explicitly name the user

services:
  # 1. The Go Backend API
  - type: web
    name: inventory-backend
    runtime: go
    rootDir: ./inventory_backend
    buildCommand: go build -o main .
    startCommand: ./main
    plan: free
    # Define the environment variables the backend needs.
    # This part correctly references the database defined above.
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString

  # 2. The React Frontend (as a Static Site served by Nginx)
  - type: web
    name: inventory-frontend
    runtime: docker
    rootDir: ./inventory-frontend
    plan: free
    # Define the environment variable for the Nginx proxy.
    # This correctly references the backend service.
    envVars:
      - key: BACKEND_HOSTPORT # Using a more descriptive key name
        fromService:
          type: web
          name: inventory-backend
          # ** UPDATED: Use the valid 'hostport' property instead of 'url' **
          property: hostport
